# This is a basic workflow to help you get started with Actions

name: checkpatch

# Controls when the workflow will run
on:
  #pull_request:
  #  types: [opened, reopened, synchronize]
  pull_request_target:
    types: [opened, synchronize, reopened, closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  skip-duplicate-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check for duplicates
        uses: fkirc/skip-duplicate-actions@v5
        with:
          key: ${{ github.event.pull_request.head.sha }}
          skip-after-success: true
          fail-on-skip: true

  checkpatch:
    uses: zhn-test/public-actions/.github/workflows/checkpatch.yml@main
    secrets: inherit
