# This is a basic workflow to help you get started with Actions

name: checkpatch

# Controls when the workflow will run
on:
  #pull_request:
  #  types: [opened, reopened, synchronize]
  pull_request_target:
    types: [opened, synchronize, reopened, closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  checkpatch:
    runs-on: ubuntu-latest
    steps:
      - name: Skip duplicate actions
        uses: fkirc/skip-duplicate-actions@v5
        with:
          key: ${{ github.event.pull_request.head.sha }}
          skip_after_successful_duplicate: true
  
      # Step 3: Run the actual checkpatch workflow (only if not skipped)
      - name: Run checkpatch
        uses: test/public-actions/.github/workflows/checkpatch.yml@main
